[package]
name = "atcoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "abc015_c"
path = "./abc/abc015/c.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
